application:
  name: captcha
  server:
    port: 7006
eureka:
  clients:
    - service-url: https://registry.orbit.com:7000/eureka
      http-basic-auth-username: admin
      http-basic-auth-password: public
redis:
  addr: redis-server.orbit.com:6379
captcha:
  height: 60
  width: 200
  mode: 2
  complex-of-noise-text: 0
  complex-of-noise-dot:  0
  use-simple-font: false
  show-hollow-line: false
  show-noise-dot: false
  show-noise-text: true
  show-slime-line: false
  show-sine-line: false
  len: 8
